#!/usr/bin/env python3

from collections import OrderedDict

import numpy as np
import pickle
import subprocess


def generate_design(npoints, ndim, ranges=None, seed=np.random.randint(2**30)):
    """
    Generate a maximin LHS design.

    """
    # use R lhs library
    output = subprocess.check_output(
        ['R', '--slave'],
        input="""
        library('lhs')
        set.seed({})
        write.table(maximinLHS({}, {}), col.names=FALSE, row.names=FALSE)
        """.format(seed, npoints, ndim).encode(),
    )

    lhs = np.array([l.split() for l in output.splitlines()], dtype=float)

    if ranges is None:
        return lhs

    # rescale hypercube to requested range
    dmin, dmax = np.asarray(ranges).T

    return lhs*(dmax - dmin) + dmin


def main():
    # design parameters and ranges
    params = OrderedDict([
        ('norm',        (   5.0,   25.0)),
        ('p',           (  -0.5,    0.5)),
        ('fluct_std',   (  1e-6,    2.0)),
        ('w',           (   0.3,    1.0)),
        ('dmin3',       (   0.0, 1.7**3)),
        ('tau_fs',      (  1e-3,    1.0)),
        ('etas_hrg',    (   0.1,    0.5)),
        ('etas_min',    (   0.0,    0.3)),
        ('etas_slope',  (   0.0,    3.0)),
        ('etas_curv',   (  -1.0,    1.0)),
        ('zetas_max',   (   0.0,    0.1)),
        ('zetas_width', (  1e-4,   0.05)),
        ('Tswitch',     (  0.13,   0.16)),
    ])

    # create design array
    design = generate_design(
        npoints=20*len(params), ndim=len(params),
        ranges=list(params.values()), seed=1052175364
    )

    # Some parameters have natural minimum == zero, but the design minimum must
    # be a small epsilon to avoid division by zero.  Now that the design array
    # is generated, replace those epsilons with actual zeroes.  Later, the GPs
    # can extrapolate and posterior dists can be plotted down to zero.
    for k in ['fluct_std', 'tau_fs', 'zetas_width']:
        params[k] = (0., params[k][1])

    # write pickle file
    with open('design.pkl', 'wb') as f:
        pickle.dump(
            dict(params=params, design=design),
            f, protocol=pickle.HIGHEST_PROTOCOL
        )

    # write OSG input files
    template = ''.join(
        '{} = {}\n'.format(key, ' '.join(args)) for (key, *args) in
        [[
            'trento_args',
            '--normalization {norm}',
            '--reduced-thickness {p}',
            '--fluctuation {k}',
            '--nucleon-width {w}',
            '--nucleon-min-dist {d}',
        ], [
            'tau_fs', '{tau_fs}'
        ], [
            'vishnew_args',
            'etas_hrg={etas_hrg}',
            'etas_min={etas_min}',
            'etas_slope={etas_slope}',
            'etas_curv={etas_curv}',
            'zetas_max={zetas_max}',
            'zetas_width={zetas_width}',
        ], [
            'Tswitch', '{Tswitch}'
        ]]
    )

    ndigits = int(np.log10(design.shape[0]) + 1)
    file_fmt = 'inputs/{:0' + str(ndigits) + 'd}'

    print('#', *params)
    for n, row in enumerate(design):
        print(*row)
        kwargs = dict(zip(params, row))
        kwargs.update(
            k=1/kwargs.pop('fluct_std')**2,
            d=kwargs.pop('dmin3')**(1/3)
        )
        with open(file_fmt.format(n), 'w') as f:
            f.write(template.format(**kwargs))


if __name__ == "__main__":
    main()
